### PR TITLE
better line erase using ANSI escape code

### PR DESCRIPTION
**Pull request by alexkubica**
I think I fixed it, checkout https://en.wikipedia.org/wiki/ANSI_escape_code.
Can you test it before merging? Also on window's powershell if possible.
Thank you!

### CODE REVIEW

**Comment by ryukinix** [comment]
@AlexK-IL Yes, I have a windows instalation on my machine. I'll test before merge it. Thanks for all efforts.

**Comment by ryukinix** [comment]
@AlexK-IL However is really common windows shell don't support ANSI escape codes...

**Comment by alexkubica** [comment]
I see, that's a shame. I'll boot into my windows and see if I can think of something else.
It did fix the output on urxvt terminal though, could you merge it anyway? Since it didn't work on windows before anyways.

**Comment by ryukinix** [comment]
This branch is out-of-date with the base branch. Rebase your branch. 

About merge it anyway I'll just test this in my machine, on linux and windows, and if it's ok I'll merge into master. Hold on a little. Would be better if we got compatibility on both terminal systems...

**Comment by ryukinix** [comment]
On linux works fine here. I don't care about Windows for today, as you said before, did not works before so this doesn't matters for now. 

Thanks for the good job!

**Comment by ryukinix** [comment]
I'll release a new version in soon on PyPI and update `mal` too. Keep calm, I'm a little busy for now unfortunately.

**Pull request merged**
